# Generated by Django 6.0.3 on 2026-03-19 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workout",
            old_name="date",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="workout",
            name="exercise",
        ),
        migrations.RemoveField(
            model_name="workout",
            name="reps",
        ),
        migrations.RemoveField(
            model_name="workout",
            name="weight",
        ),
        migrations.AddField(
            model_name="workout",
            name="title",
            field=models.CharField(default="Migracion", max_length=255),
            preserve_default=False,
        ),
    ]
