# Generated by Django 6.0.3 on 2026-03-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_profile_weightlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_pro",
            field=models.BooleanField(default=False),
        ),
    ]
