# Generated by Django 6.0.3 on 2026-04-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_profile_stripe_customer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="activity_level",
            field=models.FloatField(default=1.55),
        ),
        migrations.AddField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("M", "Hombre"), ("F", "Mujer")], default="M", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="target_calories",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="target_carbs",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="target_fat",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="target_protein",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
