# Generated by Django 6.0.3 on 2026-04-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_profile_activity_level_profile_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="height",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
