# Generated by Django 6.0.3 on 2026-04-09 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_profile_height_alter_profile_weight"),
    ]

    operations = [
        migrations.CreateModel(
            name="SleepLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("wake_time", models.CharField(default="06:30", max_length=10)),
                ("no_screens", models.BooleanField(default=False)),
                ("light_dinner", models.BooleanField(default=False)),
                ("dark_room", models.BooleanField(default=False)),
                ("supplements", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "date")},
            },
        ),
    ]
