# Generated by Django 6.0.3 on 2026-04-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_workouttemplate_templateexercise"),
    ]

    operations = [
        migrations.AddField(
            model_name="templateexercise",
            name="rest",
            field=models.IntegerField(default=90),
        ),
    ]
