# Generated by Django 6.0.3 on 2026-04-10 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_templateexercise_rest"),
    ]

    operations = [
        migrations.RenameField(
            model_name="templateexercise",
            old_name="rest",
            new_name="rest_time",
        ),
    ]
