# Generated by Django 6.0.3 on 2026-04-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_nutritionplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="unit",
            field=models.CharField(
                choices=[("kg", "kg"), ("lbs", "lbs")], default="kg", max_length=3
            ),
        ),
    ]
